### ISSUE TITLE
Graph api request - change API version

### ISSUE THREAD

**Issue by izaurek** [facebook-csharp-sdk/facebook-csharp-sdk#314]
I would like to be able to set Facebook api version in FacebookClient.
Responses sometimes depends on api versions - e.g. when I want to check permissions.

I know that in FacebookClient.Get I can put "https://graph.facebook.com/v2.1/me/permissions/" instead of "me/permissions" to make request in API v2.1 but it's easier to set version once.

BTW FacebookClient doesn't use the newest API v2.1. It's probably unversioned API but I didn't check what is sent to Facebook.

**Comment by prabirshrestha** [comment]
fixed in v7
