### ISSUE TITLE
Server-side code-to-token flow missing Version in ProcessResponse

### ISSUE THREAD

**Issue by pjuchniewicz** [facebook-csharp-sdk/facebook-csharp-sdk#324]
When checking the AbsolutePath, it is comparing it to "/oauth/access_token".  This does not take into account that a Version may be supplied.

Specified Version used: v2.0
Source\Facebook\FacebookClient.cs
Line 658
Currently: if (response.ResponseUri.AbsolutePath == "/oauth/access_token")
Locally, changed it to the following and it worked:
if (response.ResponseUri.AbsolutePath.EndsWith("/oauth/access_token", StringComparison.OrdinalIgnoreCase))

**Comment by prabirshrestha** [comment]
good catch. will work on it tonight.

**Comment by prabirshrestha** [comment]
@pjuchniewicz this should be fixed now with v7.0.3-alpha.

**Comment by hipplar** [comment]
Thanks! @prabirshrestha It's fun to see two people I know from different places working together @pjuchniewicz
