### ISSUE TITLE
WP8.1 SL MethodAccessException on method method 'Facebook.HttpHelper.UrlDecode(System.String)'

### ISSUE THREAD

**Issue by CYBERRRR** [facebook-csharp-sdk/facebook-csharp-sdk#328]
Others have also experienced this problem:
1 - http://stackoverflow.com/questions/28655465/access-method-facebook-httphelper-urldecodesystem-string-failed-winphone8
2 - http://stackoverflow.com/questions/29098070/methodaccessexception-in-using-facebook-csdk-for-windows-phone-8-1-silverlight

After being redirected from the browser to the app the following exception occurs:
```
{System.MethodAccessException: Attempt by method 'Facebook.Client.AppAuthenticationHelper.GetQueryStringValueFromUri(System.String, System.String)' to access method 'Facebook.HttpHelper.UrlDecode(System.String)' failed.   at Facebook.Client.AppAuthenticationHelper.GetQueryStringValueFromUri(String uri, String key)   at Facebook.Client.AppAuthenticationHelper.ParseQueryString(AccessTokenData session, String queryString)   at Facebook.Client.FacebookUriMapper.MapUri(Uri uri)   at System.Windows.Navigation.NavigationService.GetMappedUri(Uri uri)   at System.Windows.Navigation.NavigationService.Navigate(Uri source)}
```

Have installed HttpHelper on my project as well.

**Comment by CYBERRRR** [comment]
Sorry about the close/reopen, was thinking if moving the issue to the winclient repo would be more appropriate.

**Comment by prabirshrestha** [comment]
@CYBERRRR  please open in winclient repo

**Comment by CYBERRRR** [comment]
Moved to https://github.com/facebook-csharp-sdk/facebook-winclient-sdk/issues/73
