### ISSUE TITLE
Missing fields in FacebookApiException

### ISSUE THREAD

**Issue by talyaari** [facebook-csharp-sdk/facebook-csharp-sdk#330]
Hello, I'm using Facebook ads api SDK for .net and when I catch an error, the message is always the same general error in the exception message object: 
   (FacebookApiException - #100) Invalid parameter 
It happens since I moved to the versioned calls (v2.2) - before that I used the unversioned calls and it was fine. For example, this is how I get the error (using regular try catch in c#):
try
	{
		FacebookClient facebookClient = new FacebookClient();
		facebookClient.AccessToken = "<ACCESS_TOKEN>"

		Dictionary<string, object> parameters = new Dictionary<string, object>();
		string name = Guid.NewGuid().ToString();
		parameters.Add("name", name);
		parameters.Add("conversion_specs", "");
		parameters.Add("campaign_id", "6024570447800");
		parameters.Add("creative", "{\"creative_id\":\"6024570452200\"}");
		parameters.Add("redownload", "false");
		parameters.Add("tracking_specs", "");
		parameters.Add("view_tags", "[]");

		var result = facebookClient.Post("v2.2/act_107893676040337/adgroups", parameters) as IDictionary<string, object>;
	}
	catch (Exception ex)
	{
                FacebookApiException fbEx = ex as FacebookApiException;
		string errorMsg = fbEx.Message;
	}

It happens because Facebook changed the return error object and added 2 new fields: error_user_title, error_user_msg.
Is there a way to access these fields in the FacebookApiException  object ?
How can I extract the relevant error message?

**Comment by prabirshrestha** [comment]
@talyaari Please try v7.0.7-beta and let us know. https://www.nuget.org/packages/Facebook/7.0.7-beta

**Comment by talyaari** [comment]
@prabirshrestha Thanks for your help, 
I tried the v7.0.7-beta, I can see these 2 fields but the error message in ErrorUserMsg seemed wrong. I think it show the title (as ErrorUserTitle does) instead of the message itself.

**Comment by prabirshrestha** [comment]
@talyaari this should now be fixed in v7.0.9-beta by #332

https://www.nuget.org/packages/Facebook/7.0.9-beta

**Comment by talyaari** [comment]
Looking good. Now it's working. Thanks!
