### ISSUE TITLE
Upload Video - Tags and Place? 

### ISSUE THREAD

**Issue by tanolan** [facebook-csharp-sdk/facebook-csharp-sdk#341]
Hello,

I'm using the SDK to upload videos with "me/videos", using the publish_actions permission.  This works great, but  I'm now trying to add taggable friends and a place to the post, but I haven't been able to get this working.  I've tried the below, what am I missing? 

1. I tried adding tags and place to the "me/videos" request, thinking that might inherit from a regular post, but it doesn't work: 
client.PostTaskAsync("me/videos", new { description = postMessage, parameters.source, tags = tagsString, place = placeId });
tagsString is a comma delimited list of Taggable Friend Ids

2. After the "me/videos" request is completed, I added a ContinueWith and then made a post with the returned video postId, to add message_tags and place
client.PostTaskAsync(string.Format("/{0}", postId), new { message_tags = messageTags, place = placeId })
message_tags is a comma delimited list of Taggable Friend Ids
** The "me/videos" Task Result (in the ContinueWith) is a Success, and so is the Task Result of the post with the message_tags and place... But, neither the friend or place tags actually make it with the post.  What am I doing wrong here? 

Thank you for the help!

**Comment by tanolan** [comment]
@prabirshrestha from your other answers, I know you've worked uploading video, do you have any thoughts on this?

**Comment by prabirshrestha** [comment]
This is not a bug nor feature request. Please ask in stackoverflow.
