### ISSUE TITLE
can't search group

### ISSUE THREAD

**Issue by tudx** [facebook-csharp-sdk/facebook-csharp-sdk#347]
Can't search group now

**Comment by tudx** [comment]
This error only occur recently (it was good before), now search always return 0 in result

**Comment by prabirshrestha** [comment]
please paste some code. Also did you also verify the graph version?

**Comment by tudx** [comment]
Here are some code, I using winform c# with newest graph version

FacebookClient fb = new FacebookClient(mToken);
dynamic result = fb.Get("search", new { q = value, type = "group" });
            foreach (var item in result.data)
            {
                var obj = new GroupData
                {
                    id = item.id,
                    name = item.name
                };         
            }

**Comment by prabirshrestha** [comment]
Seems like you are not specifying the version. This could had lead to change in the api. Please be explicit in specifying the version. You can refer to it at https://github.com/facebook-csharp-sdk/facebook-csharp-sdk/pull/311#issue-40422847

**Comment by tudx** [comment]
I specifying the version, but it still don't work

 FacebookClient.DefaultVersion = "v2.0";               
                fb = new FacebookClient(mToken);
                dynamic result = fb.Get("search", new { q = "mua ban", type = "group", fields = fields, limit = mLimit });

                fb.Version = "v2.1";
                result = fb.Get("search", new { q = "mua ban", type = "group", fields = fields, limit = mLimit });

                fb.Version = "v2.2";
                result = fb.Get("search", new { q = "mua ban", type = "group", fields = fields, limit = mLimit });

                fb.Version = "v2.3";
                result = fb.Get("search", new { q = "mua ban", type = "group", fields = fields, limit = mLimit });

**Comment by tudx** [comment]
please note that this error only occur some days recently, It work well before

**Comment by prabirshrestha** [comment]
Have you tried it in the graph explorer?

https://developers.facebook.com/tools/explorer/

**Comment by tudx** [comment]
this tool seem not support search activity, how can i perform search in this

**Comment by tudx** [comment]
I tried in graph explorer tool and it also return 0, so how could I solve this error? please note that this error only occur some days recently, It work well before

**Comment by prabirshrestha** [comment]
then it is the expected behavior. SDK cannot do anything about it. Please refer to the fb docs.
