### ISSUE TITLE
How to do cursor based pagination with facebook C# sdk?

### ISSUE THREAD

**Issue by naserdostdar** [facebook-csharp-sdk/facebook-csharp-sdk#371]
Hi Everybody.
I've set a challenge for my self to retrieve all users feed posts in once but I don't know how to do cursor based pagination with facebook c# sdk. Is there any workaround. Here is what I have tried.

public async Task<ActionResult> FB_GetFeed()
        {

            var access_token = HttpContext.Items["access_token"].ToString();
            if (!string.IsNullOrEmpty(access_token))
            {
                var appsecret_proof = access_token.GenerateAppSecretProof();

                var fb = new FacebookClient(access_token);

                dynamic myFeed = await fb.GetTaskAsync(
                    ("me/feed?fields=id,from {{id, name, picture{{url}} }},story,picture,link,name,description," +
                    "message,type,created_time,likes,comments")
                    .GraphAPICall(appsecret_proof));
                var postList = new List<FacebookPostViewModel>();

                string NextPageURI = string.Empty;

                if (myFeed.paging != null &&
                    myFeed.paging.next != null)
                    NextPageURI = myFeed.paging.next;
                foreach (dynamic post in myFeed.data)
                {
                    postList.Add(DynamicExtension.ToStatic<FacebookPostViewModel>(post));
                }
                
                
                return PartialView(postList);
            }
            else
                throw new HttpException(404, "Missing Access Token");
        }

**Comment by prabirshrestha** [comment]
```c#
dynamic nextResult = await fb.Get(NextPageURI);
```
