### ISSUE TITLE
Search User by Phone

### ISSUE THREAD

**Issue by kalpesh2804** [facebook-csharp-sdk/facebook-csharp-sdk#373]
I want to search user by phone using Graph Api. 

is it possible in graph api ? 

code eg.

var fb1 = new FacebookClient(facebookOAuthResult.AccessToken);
                dynamic parameters = new ExpandoObject();
                parameters.q = "9898098980";
                parameters.type = "user";
                dynamic result1 = fb1.Get("/search", parameters);

Thanks

**Comment by prabirshrestha** [comment]
please ask on stackoverflow.
