### ISSUE TITLE
Obsolete link

### ISSUE THREAD

**Issue by oferze** [facebook-csharp-sdk/facebook-csharp-sdk#384]
The link [here](https://github.com/facebook-csharp-sdk/facebook-csharp-sdk/blob/d6bd5cb12ef53316179230adcce5a8583622b459/Build/readme.txt#L21) doesn't seem current.

It now hosts this unrelated site:

![image](https://user-images.githubusercontent.com/5157769/29753837-787be926-8b82-11e7-8d1d-05f97efbcc27.png)

**Comment by prabirshrestha** [comment]
fixed. https://github.com/facebook-csharp-sdk/facebook-csharp-sdk/commit/9d04786cb668b23d6fa0a0f01903e03ea957e723
