### ISSUE TITLE
SDK support?

### ISSUE THREAD

**Issue by projectzerotohero** [facebook-csharp-sdk/facebook-csharp-sdk#393]
Are there plans to support the newer Graph APIs?

This is the latest release so far - https://developers.facebook.com/docs/graph-api/changelog/version3.0

Also, do you have plans to support .NET Core?

**Comment by mikemike396** [comment]
+1

**Comment by jwu-au** [comment]
+1

**Comment by PatrickV82** [comment]
anyone?

**Comment by Lunster** [comment]
No doubt a project like this is a nightmare to maintain with Facebook's "move fast and break things" philosophy, and their rapidly changing APIs, as their privacy woes continue and governments worldwide continue to enforce changes.  I would imagine direct HttpCalls to Facebook's API endpoints will reduce maintenance woes long term, I realise this was the point of this SDK, and I appreciate the efforts of the authors that provided it, but this project looks abandoned.
